source "https://rubygems.org"

gem "github-pages-health-check"
gem "jekyll-coffeescript"
gem "jekyll-gist"
gem "jekyll-github-metadata"
gem "jekyll-mentions"
gem "jekyll-paginate"
gem "jekyll-redirect-from"
gem "jekyll-sass-converter"
gem "jekyll-seo-tag"
gem "jekyll-sitemap"
gem "jekyll-textile-converter"
gem "jemoji"
gem "kramdown"
gem "liquid"
gem "mercenary"
gem "rdiscount"
gem "redcarpet"
gem "RedCloth"
gem "rouge"
gem "terminal-table"
gem "jekyll", "~> 4.2.0"
gem "jekyll-avatar"
gem "jekyll-default-layout"
gem "jekyll-paginate"
gem "jekyll-mentions"
gem "jekyll-optional-front-matter"
gem "jekyll-readme-index"
gem "jekyll-redirect-from"
gem "jekyll-remote-theme"
gem "jekyll-relative-links"
gem "jekyll-titles-from-headings"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
end
