name: Sync changes to prod

on:
 push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      DEV_REPO: "zoofytech/dev.zoofytech.github.io"
      PROD_REPO: "zoofytech/zoofytech.github.io"
      PROD_REPO_NAME: "zoofytech.github.io"
      USERNAME: "zoofytech"
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: ${{ env.DEV_REPO }}
        token: ${{ secrets.GH_TOKEN }}

    - name: Check for changes
      run: |
        if ! git diff --exit-code HEAD HEAD~1; then
          echo "There have been no changes..exiting"
          exit 0
        fi

    - name: Push changes to prod repository
      run: |
        git remote add {{ env.PROD_REPO_NAME }} https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ env.PROD_REPO }}.git
        git diff --name-only HEAD HEAD~1 | xargs -I{} git push {{ env.PROD_REPO_NAME }} HEAD:{} -f
        git log -1 --pretty=%B > commit-message.txt
        git commit --amend -F commit-message.txt